export const categoryList = [
    {
      id: 1,
      value: 'wedding',
      label: ' wedding',
    },
    {
      id: 2,
      value: 'other',
      label: ' other',
    },
  ];
  
  export const ratingList = [
    {
      id: 1,
      value: '1',
      label: '1🌟',
    },
    {
      id: 2,
      value: '2',
      label: '2🌟',
    },
    {
      id: 3,
      value: '3',
      label: '3🌟',
    },
    {
      id: 4,
      value: '4',
      label: '4🌟',
    },
    {
      id: 5,
      value: '5',
      label: '5🌟',
    },
  ];
  
  export const dataList = [
    {
      id: 1,
      title: 'Wedding',  
      category: 'wedding',
      cuisine: 'Kerala',
      rating: 5,
      price: 2500,
      coverSrc: 'https://images.pexels.com/photos/3916019/pexels-photo-3916019.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    },
    {
      id: 2,
      title: 'ring exchange',
      category: 'wedding',
      cuisine: 'chennai',
      rating: 4,
      price: 12000,
      coverSrc: 'https://images.pexels.com/photos/1393478/pexels-photo-1393478.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load',
    },
    {
      id: 3,
      title: 'baby',
      category: 'wedding',
      cuisine: 'banglure',
      rating: 3,
      price: 22000,
      coverSrc: 'https://i0.wp.com/digital-photography-school.com/wp-content/uploads/2021/03/wedding-photography-tips-13.jpg?fit=1500%2C1000&ssl=1',
    },
    {
      id: 4,
      title: 'minnu',
      category: 'other',
      cuisine: 'Kerala',
      rating: 1,
      price: 12800,
      coverSrc: 'https://i0.wp.com/digital-photography-school.com/wp-content/uploads/2021/03/wedding-photography-tips-13.jpg?fit=1500%2C1000&ssl=1',
    },
    {
      id: 5,
      title: 'Wedding Photo',
      category: 'wedding',
      cuisine: 'chennai',
      rating: 5,
      price: 44000,
      coverSrc: 'https://i0.wp.com/digital-photography-school.com/wp-content/uploads/2021/03/wedding-photography-tips-13.jpg?fit=1500%2C1000&ssl=1',
    },
    {
      id: 6,
      title: 'Wedding Photo',
      category: 'other',
      cuisine: 'banglure',
      rating: 1,
      price: 74350,
      coverSrc: 'https://i0.wp.com/digital-photography-school.com/wp-content/uploads/2021/03/wedding-photography-tips-13.jpg?fit=1500%2C1000&ssl=1',
    },
    {
      id: 7,
      title: 'Wedding Photo',
      category: 'wedding',
      cuisine: 'banglure',
      rating: 2,
      price: 45500,
      coverSrc: 'https://i0.wp.com/digital-photography-school.com/wp-content/uploads/2021/03/wedding-photography-tips-13.jpg?fit=1500%2C1000&ssl=1',
    },
    {
      id: 8,
      title: 'Wedding Photo',
      category: 'other',
      cuisine: 'banglure',
      rating: 3,
      price: 11500,
      coverSrc: 'https://i0.wp.com/digital-photography-school.com/wp-content/uploads/2021/03/wedding-photography-tips-13.jpg?fit=1500%2C1000&ssl=1',
    },
    {
      id: 9,
      title: 'Wedding Photo',
      category: 'wedding',
      cuisine: 'banglure',
      rating: 3,
      price: 35200,
      coverSrc: 'https://i0.wp.com/digital-photography-school.com/wp-content/uploads/2021/03/wedding-photography-tips-13.jpg?fit=1500%2C1000&ssl=1',
    },
    {
      id: 10,
      title: 'Wedding Photo',
      category: 'wedding',
      cuisine: 'kerala',
      rating: 5,
      price: 35200,
      coverSrc: 'https://i0.wp.com/digital-photography-school.com/wp-content/uploads/2021/03/wedding-photography-tips-13.jpg?fit=1500%2C1000&ssl=1',
    },
    {
      id: 11,
      title: 'Wedding Photo',
      category: 'other',
      cuisine: 'banglure',
      rating: 4,
      price: 43500,
      coverSrc: 'https://i0.wp.com/digital-photography-school.com/wp-content/uploads/2021/03/wedding-photography-tips-13.jpg?fit=1500%2C1000&ssl=1',
    },
    {
      id: 12,
      title: 'Wedding Photo',
      category: 'other',
      cuisine: 'kerala',
      rating: 2,
      price: 34500,
      coverSrc: 'https://i0.wp.com/digital-photography-school.com/wp-content/uploads/2021/03/wedding-photography-tips-13.jpg?fit=1500%2C1000&ssl=1',
    },
    {
      id: 13,
      title: 'Wedding Photo',
      category: 'other',
      cuisine: 'banglure',
      rating: 1,
      price: 32500,
      coverSrc: 'https://i0.wp.com/digital-photography-school.com/wp-content/uploads/2021/03/wedding-photography-tips-13.jpg?fit=1500%2C1000&ssl=1',
    },
    {
      id: 14,
      title: 'Wedding Photo',
      category: 'wedding',
      cuisine: 'kerala',
      rating: 2,
      price: 13500,
      coverSrc: 'https://i0.wp.com/digital-photography-school.com/wp-content/uploads/2021/03/wedding-photography-tips-13.jpg?fit=1500%2C1000&ssl=1',
    },
   
  ];